apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-home
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
spec:
  tls:
  - hosts:
    - "{{ .Values.domain }}"
  rules:
  - host: "{{ .Values.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testnet-homepage
            port:
              number: 1313
