apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-faucet
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
spec:
  tls:
  - hosts:
    - "faucet.{{ .Values.domain }}"
  rules:
  - host: "faucet.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fauceth
            port:
              number: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-faucet-request
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"

spec:
  tls:
  - hosts:
    - "faucet.{{ .Values.domain }}"
  rules:
  - host: "faucet.{{ .Values.domain }}"
    http:
      paths:
      - path: /request
        pathType: Exact
        backend:
          service:
            name: haproxy
            port:
              number: 80
